apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-receiver
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"  
        autoscaling.knative.dev/max-scale: "1"  
    spec:
      containers:
      - image: quay.io/openshift-knative/knative-eventing-sources-event-display
---



























































# apiVersion: v1
# kind: Service
# metadata:
#   name: event-receiver
# spec:
#   selector:
#     app: event-receiver
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: event-receiver
#       name: http

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: event-receiver
#   labels:
#     app: event-receiver
# spec:
#   containers:
#   - name: event-receiver
#     image: quay.io/openshift-knative/knative-eventing-sources-event-display
#     imagePullPolicy: Always
#     ports:
#     - containerPort: 8080
#       protocol: TCP
#       name: event-receiver
