apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: my-dls-kafka-broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: my-dls-kafka-broker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-dls-kafka-broker-config
data:
  bootstrap.servers: my-cluster-kafka-bootstrap.kafka:9092
  default.topic.partitions: "10"
  default.topic.replication.factor: "3"

