apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: my-demo-kafka-broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: my-demo-kafka-broker-config
  delivery:
    deadLetterSink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: my-dls-kafka-broker


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-demo-kafka-broker-config
data:
  bootstrap.servers: my-cluster-kafka-bootstrap.kafka:9092
  default.topic.partitions: "10"
  default.topic.replication.factor: "3"

