apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-one
spec:
  broker: my-demo-kafka-broker
  # filter:
  #   attributes:
  #     type: com.wjax
  #     smartevent: foo
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-receiver

